services:
    app:
        image: 'bitnami/laravel:latest'
        container_name: laravel_app
        environment:
            - APP_ENV=LOCAL
            - APP_DEBUG=TRUE
            - DB_CONNECTION=mysql
            - DB_HOST=mariadb
            - DB_PORT=3306
            - DB_DATABASE=heimdall
            - DB_USERNAME=heimdall
            - DB_PASSWORD=heimdall
        volumes:
            - '.:/app'
        ports:
            - '8000:8000'
        depends_on:
            - mariadb
            - soketi
    mariadb:
        image: 'mariadb:latest'
        container_name: mariadb
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_DATABASE=heimdall
            - MYSQL_USER=heimdall
            - MYSQL_PASSWORD=heimdall
        ports:
            - '3306:3306'
        volumes:
            - 'db_data:/var/lib/mysql'
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
volumes:
    db_data: null
    redis_data: null
