services:
    app:
        image: 'ovicorsho/heimdall:0.1'
        environment:
            - APP_ENV=LOCAL
            - APP_DEBUG=TRUE
            - DB_HOST=mariadb
            - DB_DATABASE=heimdall
            - DB_USERNAME=heimdall
            - DB_PASSWORD=heimdall
        ports:
            - '8000:8000'
        depends_on:
            - mariadb
            - redis
            - soketi
        networks:
            - heimdall-network

    mariadb:
        image: 'mariadb:latest'
        environment:
            - MARIADB_RANDOM_ROOT_PASSWORD=TRUE
            - MARIADB_DATABASE=heimdall
            - MARIADB_USER=heimdall
            - MARIADB_PASSWORD=heimdall
        ports:
            - '3306:3306'
        volumes:
            - './db_data:/var/lib/mysql'
        restart: always
        networks:
            - heimdall-network
    soketi:
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        ports:
            - '6001:6001'
            - '9601:9601'
        depends_on:
            - mariadb
            - redis
        volumes:
            - './soketi.env:/app/.env'
        networks:
            - heimdall-network
    redis:
        image: 'redis:7.2-alpine'
        volumes:
            - './redis_data:/data'
        networks:
            - heimdall-network

networks:
    heimdall-network:
        driver: bridge
